comp_status:
  description: Component status
  value:
    type: choice
    default: Enabled
    choices:
    - Enabled
    - Disabled
    units: '-'
in_directory:
  description: Input directory
  value:
    type: string
    default: permamodel/examples
    units: '-'
out_directory:
  description: Output directory
  value:
    type: string
    default: .
    units: '-'
permafrost_dir:
  description: permafrost directory
  value:
    type: string
    default: .
    units: '-'    
site_prefix:
  description: File prefix for the study site
  value:
    type: string
    default: Case_test
    units: '-'
case_prefix:
  description: File prefix for the model scenario
  value:
    type: string
    default: Case_test
    units: '-'
lat_type:
  description: latitude 
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    units: '-'
lat:
  description: latitude
  value:
    type: float
    default: 64.8378
    range:
      min: -90.0
      max: 90
    units: '-'    
lon_type:
  description: longitude 
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    units: '-'
lon:
  description: longitude
  value:
    type: float
    default: -147.7164
    range:
      min: -180.0
      max: 180
    units: '-'
start_year:
  description: begining of the simulation time 
  value:
    type: float
    default: 2009
    range:
      min: 0
      max: 100000000
    units: year
end_year:
  description: end of the simulation time 
  value:
    type: float
    default: 2009
    range:
      min: 0
      max: 100000000
    units: year
dt:
  description: Timestep for infiltration process (a year)
  value:
    type: float
    default: 31536000.000
    range:
      min: 0
      max: 1e12
    units: sec
T_air_type:
  description: Near Surface Air Temperature input types
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
T_air:
  description: Near Surface Air Temperature (annual mean)
  value:
    type: float
    default: -9.0
    range:
      min: -100.0
      max: 100
    units: degC
A_air_type:
  description: Near Surface Air Temperature Amplitude input types
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
A_air:
  description: Near Surface Air Temperature Amplitude (annual)
  value:
    type: float
    default: 15.4
    range:
      min: -100.0
      max: 100
    units: degC
h_snow_type:
  description: Allowed input types
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
h0_snow:
  description: Depth of snow (average through winter)
  value:
    type: float
    default: 0.300
    range:
      min: 0.0
      max: 5.0
    units: m
rho_snow_type:
  description: Allowed input types
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
rho_snow:
  description: Density of snow (average through winter)
  value:
    type: float
    default: 240.000
    range:
      min: 0.0
      max: 1e3
    units: kg/m^3
vwc_H2O_type:
  description: Allowed input types
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
vwc_H2O:
  description: Soil volumetric water content (thaw season, eg. August)
  value:
    type: float
    default: 0.40
    range:
      min: 0.0
      max: 1.0
    units: '-'
Hvgf_type:
  description: Allowed input types
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
Hvgf_type:
  description: Height of vegetation in frozen period
  value:
    type: float
    default: 0.00
    range:
      min: 0.0
      max: 1.0
    units: 'm'
Hvgt_type:
  description: Allowed input types
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
Hvgt_type:
  description: Height of vegetation in thawed period
  value:
    type: float
    default: 0.00
    range:
      min: 0.0
      max: 1.0
    units: 'm'
Dvf_type:
  description: Allowed input types
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
Dvf_type:
  description: Thermal diffusivity of vegetation in frozen period
  value:
    type: float
    default: 1.39E-6
    range:
      min: 0.0
      max: 5.0E-6
    units: 'm2 s'
Dvt_type:
  description: Allowed input types
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
Dvt_type:
  description: Thermal diffusivity of vegetation in frozen period
  value:
    type: float
    default: 5.56E-8
    range:
      min: 0.0
      max: 1.0E-6
    units: 'm2 s'
SAVE_ALT_GRIDS:
  description: option to save result or not
  value:
    type: choice
    default: Scalar
    choices:
    - Yes
    - No
    units: '-'
ALT_file:
  description: Name of output file
  value:
    type: string
    default: ALT.nc
    units: '-'    
ModelName:
  description: Name of the model
  value:
    type: String
    default: Ku_model
    units: '-'
ModelAuthor:
  description: Name of the model author
  value:
    type: String
    default: 'Kang Wang & Elchin E. Jafarov'
    units: '-'
HTML_HELP_FILE:
  description: Url for html help file
  value:
    type: String
    default: http://csdms.colorado.edu/wiki/
    units: '-'