language: python
python:
  - "2.7"
sudo: false
before_install:
  - pip install nose
  - pip install numpy
  - pip install netCDF4
  - pip install scipy
  - pip install affine
install:
  - python setup.py install
script:
  - nosetests
