language: python
python:
  - "2.7_with_system_site_packages"
before_install:
  - sudo apt-get install -qq python-numpy python-scipy
  - pip install nose
  - pip install netCDF4
  - pip install affine
install:
  - python setup.py install
script:
  - nosetests
