permafrost_dir:
  description: Directory containing permamodel files
  value:
    type: string
    default: .
    units: '-'
comp_status:
  description: Component status
  value:
    type: choice
    default: Enabled
    choices:
    - Enabled
    - Disabled
    units: '-'
in_directory:
  description: Input directory
  value:
    type: string
    default: .
    units: '-'
out_directory:
  description: Output directory
  value:
    type: string
    default: .
    units: '-'
site_prefix:
  description: File prefix for the study site
  value:
    type: string
    default: Test
    units: '-'
case_prefix:
  description: File prefix for the model scenario
  value:
    type: string
    default: Case_test
    units: '-'
T_air_min_ptype:
  description: Average temperature of coldest month in the modeled year
  value:
    type: choice
    default: Scalar
    choices:
      - Scalar
      - Time_Series
    units: degC
T_air_min_dtype:
  description: T_air_min data type
  value:
    type: choice
    default: float
    choices:
      - float
      - int
      - long
      - string
    units: '-'
T_air_min:
  description: Scalar value
  value:
    type: float
    default: -9.0
    range:
      min: -100.0
      max: 100.0
    units: degC
T_air_min_file:
  description: Time series file
  value:
    type: file
    default: 'off'
    files:
      - 'off'
T_air_max_ptype:
  description: Average temperature of warmest month in the modeled year
  value:
    type: choice
    default: Scalar
    choices:
      - Scalar
      - Time_Series
    units: degC
T_air_max_dtype:
  description: T_air_max data type
  value:
    type: choice
    default: float
    choices:
      - float
      - int
      - long
      - string
    units: '-'
T_air_max:
  description: Scalar value
  value:
    type: float
    default: -9.0
    range:
      min: -100.0
      max: 100.0
    units: degC
T_air_max_file:
  description: Time series file
  value:
    type: file
    default: 'off'
    files:
      - 'off'
start_year:
  description: begining of the simulation time 
  value:
    type: long
    default: 2000
    range:
      min: 1000
      max: 2200
    units: year
end_year:
  description: end of the simulation time 
  value:
    type: long
    default: 2000
    range:
      min: 1000
      max: 2200
    units: year
dt:
  description: Timestep for permamodel
  value:
    type: float
    default: 1.0
    range:
      min: 0.001
      max: 1e3
    units: year
