permafrost_dir:
  description: Directory containing permamodel files
  value:
    type: string
    default: .
    units: '-'
comp_status:
  description: Component status
  value:
    type: choice
    default: Enabled
    choices:
    - Enabled
    - Disabled
    units: '-'
in_directory:
  description: Input directory
  value:
    type: string
    default: .
    units: '-'
out_directory:
  description: Output directory
  value:
    type: string
    default: .
    units: '-'
site_prefix:
  description: File prefix for the study site
  value:
    type: string
    default: Test
    units: '-'
case_prefix:
  description: File prefix for the model scenario
  value:
    type: string
    default: Case_test
    units: '-'
T_air_min_type:
  description: data type of T_air_min
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Time_Series
    units: '-'
T_air_min:
  description:  Average temp of coldest month in the modeled year
  value:
    type: float
    default: -9.0
    range:
      min: -100.0
      max: 100.0
    units: degC
T_air_max_type:
  description: date type of T_air_max
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Time_Series
    units: '-'
T_air_max:
  description:  Average temp of warmest month in the modeled year
  value:
    type: float
    default: 15.4
    range:
      min: -100.0
      max: 100.0
    units: degC
start_year:
  description: begining of the simulation time 
  value:
    type: float
    default: 2000.0
    range:
      min: 1000.0
      max: 2200.0
    units: year
end_year:
  description: end of the simulation time 
  value:
    type: float
    default: 2000.0
    range:
      min: 1000.0
      max: 2200.0
    units: year
dt:
  description: Timestep for permamodel
  value:
    type: float
    default: 1.0
    range:
      min: 0.001
      max: 1e3
    units: year
